# Generated by Django 4.2.5 on 2023-09-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('coin', models.CharField(blank=True, max_length=15, null=True)),
                ('safoa_byte', models.CharField(blank=True, max_length=800, null=True, unique=True)),
                ('safoa', models.CharField(blank=True, max_length=800, null=True, unique=True)),
                ('purpose', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('address_type', models.CharField(blank=True, max_length=20, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('migrated', models.BooleanField(default=False)),
                ('amount_owed', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('reason_for_lock', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('sender_address', models.CharField(blank=True, max_length=75, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16)),
                ('amount_fiat', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('cli_label', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('coin', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('double_spend', models.BooleanField(default=False)),
                ('txid', models.CharField(blank=True, max_length=100, null=True)),
                ('tx_link', models.CharField(blank=True, max_length=300, null=True)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('ack', models.BooleanField(default=False)),
            ],
        ),
    ]
