# Generated by Django 4.2.4 on 2023-09-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='amount_fiat',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=16),
        ),
    ]
