# Generated by Django 4.2.5 on 2023-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrp', '0004_lastprocessedledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastprocessedledger',
            name='ledger',
            field=models.IntegerField(default=82398496),
        ),
    ]
